### ISSUE TITLE
Error in hclust

### ISSUE THREAD

**Issue by EzicJ** [stemangiola/tidyHeatmap#2] opened 2020-04-02 10:34 UTC
Hi, first of all, thanks for the awesome package.

I have this issue coming up, and don't know how to resolve it.
Unfortunately, because of the circumstances, I can't share a reproducible example here, but my dataframe is tbl_df format, my values are ranging from 0 to 1, and there are no NAs.

When I want to make a heatmap I get:

```
Error in hclust(get_dist(submat, distance), method = method) : 
  NA/NaN/Inf in foreign function call (arg 10)
```
What causes the error?
Thanks a lot!

**Comment by stemangiola** [comment] 2020-04-02 11:05
Hello,

one thing you can do is to look at the example data set that is in the package (README), and see 
if there is something obvious compared with your dataset.

This is an error of ComplexHeatmap package itself, so you can do 

1) debug(heatmap)
2) run your function
3) goto the point of where Heatmap (from ComplexHeatmap) is called and see what is strange with the numerical matrix.

Please let me know as I could be able to implement some checks.

If you can please send me the anonimised dataset at mangiolastefano@gmail.com I will be able to help you better

**Comment by marcora** [comment] 2020-04-08 15:53
I am running into the same problem and this is likely due to the fact that not all combinations of "horizontal" and "vertical" variables may appear in your dataframe, hence returning NAs as the "abundance" of missing combinations that hclust cannot handle. It would be nice to have the possibility of specifying a value or function to use as "abundance" value when a combination is missing.

Please advise.

**Comment by stemangiola** [comment] 2020-04-08 23:09
Hello. If this is the problem users most run into it should pretty easy. I can add

- A check to see if the data is rectangular (internal **check_if_data_rectangular** from tidybulk)
- And I could fill the missing genes with median value, and through a warning.

Could you please tell me the outcome of applying this function 

```r
check_if_data_rectangular = function(.data, .sample, .transcript, .abundance, type = "hard"){

	# Parse column names
	.sample = enquo(.sample)
	.transcript = enquo(.transcript)
	.abundance = enquo(.abundance)

	is_rectangular =
		.data %>%
		distinct(!!.sample, !!.transcript, !!.abundance) %>%
		count(!!.sample) %>%
		count(n) %>%
		nrow %>%
		equals(1)

	is_rectangular

	# if(!is_rectangular & type == "hard") stop("tidybulk says: the data must have the same number of transcript per sample.")
	#
	# if(!is_rectangular & type == "soft") warning("tidybulk says: the data should have the same number of transcript per sample.")


	# # Eliminate sparse transcripts
	# .data %>% eliminate_sparse_transcripts(!!.transcript)


}
```

On your dataset? Where .sample, .transcript, .abundance are column names

**Comment by stemangiola** [comment] 2020-04-09 01:00
Hello Folks.

I have introduced a validation routine for the input data set (dev branch). Now if the data is not rectangular the sparse vertical features are removed with suggestion 

```If you want to impute missing data use tidybulk::impute_abundance(~1, .horizontal, .vertical, .abundance)```

If you want to have it for the moment please install dev branch devtools::install_github("stemangiola/tidyHeatmap@dev)

Please let me know how you go, if you are OK I will merge into master branch

**Comment by marcora** [comment] 2020-04-09 14:52
I'd say that, while of course tidyHeatmap can be used for plotting abundances, it can be used (and I am using it) to display other type of data. Beside imputation, I would add a parameter in the function call to specify either 1) a fixed value or 2) a function that is used to replace NA in the missing sample-transcript combinations.

I understand that tidyHeatmap originated from a RNA-Seq focused project, but I would recommend generalizing it for more generic use cases.

**Comment by stemangiola** [comment] 2020-04-10 06:05
Few comments:

- this package has the aim to be non-biological. This is the reason I have put it on CRAN (ComplexHeatmap for some reason is in Bioconductor). For going toward this direction not .abundance is soft deprecated in favor of .value
- this package is a wrapper of the Heatmap function, imputing or replacing missing data is not in the scope of the pakage. In the future another package `aupair` will allow you this kind of high-level manipulations. In the meanwhile you can either use tidybulk (in absence of anything better), or code the correction yourself, which in tidyverse is pretty easy

```
.data %>%
		select(element, feature, value) %>%
		distinct %>%
		spread(feature, value) %>%
		gather(feature, value, element) %>%
                mutate(value = ifelse(value %>% is.na, <YOUR_VALUE>, value))
```

**Comment by marcora** [comment] 2020-04-10 18:57
Yes, that's what I am doing now. But it would help people with less
experience (like wet lab biologists who want to plot a heatmap) having an
error code warning of the problem (like you proposed) and a simple solution
using a parameter (replace_na = value) in the function call to quickly fix
the problem.

**Comment by stemangiola** [comment] 2020-04-11 00:08
@marcora thanks for your feedback. I will have to think about concrete use cases for the benefit of adding a new parameter.

I'll close this issue as the original problem has been solved. If you wish to ask new features please open another issue, with some example of its relevance.

Thanks.

**Comment by marcora** [comment] 2020-04-22 18:51
I am reopening this issue because it could be simply dealt with by the fact that ComplexHeatmap can actually handle NAs when clustering and display them in gray (or other color as specified in na_col parameter).

It would be very helpful if tidyHeatmap could take advantage of this functionality and thus generate a plot (while still issuing the warning) even when NA values are present.

See https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html

**Comment by stemangiola** [comment] 2020-04-23 07:31
Implemented your concept in dev branch.

Please confirm. Afterwards I will merge to master.

**Comment by stemangiola** [comment] 2020-04-28 03:00
I assume the issue is solve. Closing in.

**Closed by stemangiola** 2020-04-28 03:00 UTC
Labels: bug
